name: build-containers

on:
  push:
#    branches: [ main ]
    tags:     [ 'v*' ]
    paths-ignore:
      - '**.adoc'
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build-containers:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'centos-7-amd64'
          - 'centos-8-amd64'
          - 'centos-9-amd64'
          - 'fedora-35-amd64'
          - 'fedora-36-amd64'
          - 'debian-11-amd64'
          - 'debian-11-i386'
          - 'debian-10-i386'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./${{ matrix.container }}.Dockerfile
          push: ${{ contains(github.ref, 'refs/tags/v') }}
          tags: ghcr.io/${{ github.actor }}/ci-rnp-${{ matrix.container }}
          labels: |
            latest
            "org.opencontainers.image.source=${{ github.repositoryUrl }}"

      - name: Purge old versions
        if: contains(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ci-rnp-${{ matrix.container }}'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
